name: No Dramas Investments
favicon: null
layout_spectrum: 0.88037
typography_spectrum: 0.64781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bed8f9'
    - '#71b3d6'
    - '#181725'
    - '#234077'
    - '#927d94'
  brandStrength: 0.25
  lightness: 0.6108818538486958
  saturation: 0.49727149424143136
  rhythmicContrast: 0.7608585397247225
purpose: []
